"""Thin runtime adapter boundary shared by execution engines."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Adapter(Protocol):
    """Execution and catalog operations required from a Skifer adapter."""

    @property
    def name(self) -> str:
        """Return the adapter's short identity."""
        ...

    @property
    def capabilities(self) -> frozenset[str]:
        """Return the capabilities declared by this adapter."""
        ...

    def fetch(self, query: str) -> list[dict]: ...

    def execute_sql(self, sql: str) -> Any: ...

    def sql(self, query: str) -> Any: ...

    def read_table(self, fqn: str) -> Any: ...

    def write_table(self, df: Any, fqn: str, mode: str = "overwrite") -> None: ...

    def table_exists(self, catalog: str | None, schema: str, table: str) -> bool: ...

    def schema_exists(self, catalog: str | None, schema: str) -> bool: ...

    def ensure_schema_exists(self, schema: str) -> None: ...

    def list_tables(self, schema: str, catalog: str | None = None) -> list[str]: ...

    def list_columns(self, fqn: str) -> list[str]: ...

    def list_relation_columns(self, relation: str) -> list[str]: ...

    def list_schemas(self, catalog: str | None = None) -> list[str]: ...

    def list_column_types(self, fqn: str) -> dict[str, str]: ...

    def build_fqn(self, catalog: str | None, schema: str, table: str) -> str: ...

    def drop_table(self, fqn: str) -> None: ...

    def clone_table(
        self,
        src_catalog: str | None,
        src_schema: str,
        src_table: str,
        tgt_catalog: str | None,
        tgt_schema: str,
        tgt_table: str,
    ) -> None: ...

    def register_temp_view(self, df: Any, name: str) -> None: ...

    def get_current_user(self) -> str | None: ...
