"""
OrchestratorExporter — génère des artefacts d'orchestration depuis des YAML de pipeline.

Trois niveaux de sortie (du plus universel au plus natif) :
  1. Airflow DAG Python (opérateur Databricks)
  2. Databricks Asset Bundle YAML (natif Spark/Databricks, optionnel)
  3. Python script fallback (aucune dépendance — toujours généré)

Stratégie de sélection :
  Backend détecté       Format primaire              Fallback
  ─────────────────────────────────────────────────────────────────
  Spark / Databricks    Airflow DAG + DAB YAML       Python script
  Local                 Python script uniquement
"""
from __future__ import annotations

import os
import re
from typing import TYPE_CHECKING

from skifer.agentic.models import OrchestratorExportResult

if TYPE_CHECKING:
    from skifer.core.spark_backend import SparkBackend


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _pipeline_name(yaml_path: str) -> str:
    """Derive a valid Python identifier from a YAML file path."""
    stem = os.path.splitext(os.path.basename(yaml_path))[0]
    return re.sub(r"[^a-zA-Z0-9_]", "_", stem)


def _detect_backend_type(backend: "SparkBackend") -> str:
    """
    Detect the execution mode of the (Spark) backend.

    Returns "spark" for a remote Databricks backend, "local" otherwise
    (local Spark session or test double).
    """
    cls_name = type(backend).__name__.lower()
    if "spark" in cls_name:
        return "local" if getattr(backend, "is_local", False) else "spark"
    return "local"


# ---------------------------------------------------------------------------
# Airflow DAG generator
# ---------------------------------------------------------------------------

def _render_airflow_dag(
    pipeline_names: list[str],
    backend_type: str,
    dag_id: str = "skifer_pipelines",
) -> str:
    """Render an Airflow DAG Python file for the given pipeline names."""
    if backend_type == "spark":
        operator_import = (
            "from airflow.providers.databricks.operators.databricks "
            "import DatabricksRunNowOperator"
        )
        task_template = (
            '    {name} = DatabricksRunNowOperator(\n'
            '        task_id="{name}",\n'
            '        job_id=0,  # TODO: set Databricks job ID\n'
            '    )\n'
        )
    else:
        operator_import = "from airflow.operators.python import PythonOperator"
        task_template = (
            '    {name} = PythonOperator(\n'
            '        task_id="{name}",\n'
            '        python_callable=lambda: None,  # TODO: call run_pipeline("{name}")\n'
            '    )\n'
        )

    tasks_code = "".join(task_template.format(name=n) for n in pipeline_names)

    if len(pipeline_names) > 1:
        chain = " >> ".join(pipeline_names)
        dep_code = f"\n    {chain}\n"
    else:
        dep_code = ""

    return (
        '"""\nGenerated by Skifer — OrchestratorExporter.\n"""\n'
        "from airflow import DAG\n"
        f"{operator_import}\n"
        "from datetime import datetime\n\n"
        f'with DAG("{dag_id}", start_date=datetime(2026, 1, 1), schedule="@daily") as dag:\n'
        f"{tasks_code}"
        f"{dep_code}"
    )


# ---------------------------------------------------------------------------
# Databricks Asset Bundle generator
# ---------------------------------------------------------------------------

def _render_dab_bundle(pipeline_names: list[str], bundle_name: str = "skifer_pipelines") -> str:
    """Render a Databricks Asset Bundle YAML file."""
    tasks = ""
    for name in pipeline_names:
        tasks += (
            f"        - task_key: {name}\n"
            f"          notebook_task:\n"
            f"            notebook_path: notebooks/{name}\n"
            f"          depends_on: []\n"
        )

    return (
        f"bundle:\n"
        f"  name: {bundle_name}\n\n"
        f"resources:\n"
        f"  jobs:\n"
        f"    {bundle_name}:\n"
        f"      name: {bundle_name}\n"
        f"      tasks:\n"
        f"{tasks}"
    )


# ---------------------------------------------------------------------------
# Python script fallback generator
# ---------------------------------------------------------------------------

def _render_python_script(yaml_paths: list[str]) -> str:
    """Render a standalone Python script that runs all pipelines sequentially."""
    lines = [
        '"""',
        "Generated by Skifer — OrchestratorExporter.",
        'Run with: python run_pipelines.py',
        '"""',
        "from skifer import SkiferEngine, load_schema",
        "",
        'engine = SkiferEngine("config.yaml")',
        "",
    ]
    for path in yaml_paths:
        name = _pipeline_name(path)
        lines += [
            f"# Pipeline: {name}",
            f'schema_{name} = load_schema("{path}", params=engine.default_params)',
            f"engine.run_process_to_table(schema_{name})",
            "",
        ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# OrchestratorExporter
# ---------------------------------------------------------------------------

class OrchestratorExporter:
    """
    Generates orchestration artefacts for a list of Skifer pipeline YAMLs.

    Usage::

        from skifer.agentic.orchestrator import OrchestratorExporter
        exporter = OrchestratorExporter(backend=engine._backend)
        result = exporter.export(["schemas/silver/orders.yaml"], output_dir="orchestration")
    """

    def __init__(self, backend: "SparkBackend | None" = None):
        self._backend = backend
        self._backend_type = _detect_backend_type(backend) if backend else "local"

    def export(
        self,
        yaml_paths: list[str],
        output_dir: str = "orchestration",
        format: str = "auto",
    ) -> OrchestratorExportResult:
        """
        Generate orchestration artefacts for a list of pipeline YAML paths.

        Args:
            yaml_paths:  List of YAML schema file paths to orchestrate.
            output_dir:  Directory where artefacts are written.
            format:      "auto" | "airflow" | "databricks" | "script"
                         "auto" selects the best format based on the detected backend.

        Returns:
            OrchestratorExportResult with paths to generated files.
        """
        if not yaml_paths:
            raise ValueError("yaml_paths must not be empty.")

        backend_type = self._backend_type
        resolved_format = self._resolve_format(format, backend_type)
        pipeline_names = [_pipeline_name(p) for p in yaml_paths]

        os.makedirs(output_dir, exist_ok=True)

        # Always generate the Python fallback script
        script_content = _render_python_script(yaml_paths)
        script_path = os.path.join(output_dir, "scripts", "run_pipelines.py")
        os.makedirs(os.path.dirname(script_path), exist_ok=True)
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script_content)

        if resolved_format == "script":
            return OrchestratorExportResult(
                format="script",
                primary_path=script_path,
                fallback_script_path=script_path,
                pipelines=list(yaml_paths),
            )

        # Generate Airflow DAG (Databricks operator)
        dag_id = "skifer_pipelines"
        dag_content = _render_airflow_dag(pipeline_names, backend_type, dag_id=dag_id)
        dag_path = os.path.join(output_dir, "airflow", f"dag_{dag_id}.py")
        os.makedirs(os.path.dirname(dag_path), exist_ok=True)
        with open(dag_path, "w", encoding="utf-8") as f:
            f.write(dag_content)

        # Optionally generate Databricks Asset Bundle
        if resolved_format == "databricks":
            bundle_content = _render_dab_bundle(pipeline_names)
            bundle_path = os.path.join(output_dir, "databricks", "bundle.yml")
            os.makedirs(os.path.dirname(bundle_path), exist_ok=True)
            with open(bundle_path, "w", encoding="utf-8") as f:
                f.write(bundle_content)
            return OrchestratorExportResult(
                format="databricks",
                primary_path=bundle_path,
                fallback_script_path=script_path,
                pipelines=list(yaml_paths),
            )

        return OrchestratorExportResult(
            format="airflow",
            primary_path=dag_path,
            fallback_script_path=script_path,
            pipelines=list(yaml_paths),
        )

    def _resolve_format(self, format: str, backend_type: str) -> str:
        """Resolve 'auto' to the most appropriate format for the backend."""
        if format != "auto":
            return format
        if backend_type == "spark":
            return "databricks"
        return "script"
