"""Governed capability schemas and lazy catalog access."""

from .autonomy import (
    ApprovalError,
    ApprovalRecord,
    AutonomyError,
    AutonomyMode,
    AutonomyStateMachine,
    ExecutionState,
    TransitionError,
    precondition_hash,
    request_hash,
    resolve_autonomy_mode,
    validate_approval,
)

from .models import (
    ActingAs,
    ApprovalMode,
    CapabilityDefinition,
    CapabilityMode,
    CapabilitySummary,
    Reversibility,
)
from .executors import (
    CapabilityExecutorError,
    CapabilityExecutorRegistry,
    CapabilityResult,
)
from .credentials import (
    MAX_ACTIVE_CREDENTIAL_LEASES,
    MAX_CREDENTIAL_TTL,
    CredentialBroker,
    CredentialError,
    CredentialLease,
    CredentialProvider,
    assert_no_credential_for_shadow,
)
from .invoker import CapabilityInvoker, validate_arguments
from .executor import (
    DuplicateRequestError,
    GovernedExecutionError,
    GovernedExecutor,
    LostResponseError,
)
from .history import (
    MAX_EVENT_DETAIL_BYTES,
    MAX_HISTORY_PAGE_SIZE,
    CapabilityHistoryError,
    CapabilityHistoryStore,
    CapabilityStateEvent,
    SqliteCapabilityHistoryStore,
)
from .harness import (
    CapabilityHarness,
    CapabilityScenario,
    HarnessReport,
    ScenarioClockError,
    ScenarioClockExhausted,
    ScenarioExpectation,
    ScenarioObservation,
    ScenarioResult,
)
from .preconditions import (
    PreconditionDecision,
    PreconditionError,
    PreconditionEvaluator,
    PreconditionOutcome,
    PreconditionRegistry,
    PreconditionReport,
)
from .registry import CapabilityRegistry, CapabilityRegistryError
from .validator import (
    CapabilityValidationError,
    CapabilityValidator,
    ValidationResult,
    parse_capability,
)

__all__ = [
    "ActingAs",
    "ApprovalMode",
    "ApprovalError",
    "ApprovalRecord",
    "CapabilityDefinition",
    "CapabilityExecutorError",
    "CapabilityExecutorRegistry",
    "CapabilityInvoker",
    "CapabilityHistoryError",
    "CapabilityHistoryStore",
    "CapabilityHarness",
    "CapabilityMode",
    "CapabilityRegistry",
    "CapabilityRegistryError",
    "CapabilityResult",
    "CapabilityScenario",
    "CapabilitySummary",
    "CapabilityStateEvent",
    "CapabilityValidationError",
    "CapabilityValidator",
    "CredentialBroker",
    "CredentialError",
    "CredentialLease",
    "CredentialProvider",
    "DuplicateRequestError",
    "GovernedExecutionError",
    "GovernedExecutor",
    "HarnessReport",
    "AutonomyError",
    "AutonomyMode",
    "AutonomyStateMachine",
    "ExecutionState",
    "MAX_ACTIVE_CREDENTIAL_LEASES",
    "MAX_CREDENTIAL_TTL",
    "MAX_EVENT_DETAIL_BYTES",
    "MAX_HISTORY_PAGE_SIZE",
    "PreconditionDecision",
    "PreconditionError",
    "PreconditionEvaluator",
    "PreconditionOutcome",
    "PreconditionRegistry",
    "PreconditionReport",
    "Reversibility",
    "ScenarioClockError",
    "ScenarioClockExhausted",
    "ScenarioExpectation",
    "ScenarioObservation",
    "ScenarioResult",
    "LostResponseError",
    "SqliteCapabilityHistoryStore",
    "TransitionError",
    "ValidationResult",
    "assert_no_credential_for_shadow",
    "parse_capability",
    "precondition_hash",
    "request_hash",
    "resolve_autonomy_mode",
    "validate_approval",
    "validate_arguments",
]
